### ISSUE TITLE
[Feature Suggestion] Icons for each class

### ISSUE THREAD

**Issue by GhostwheelX** [MrEnigmamgine/spell-class-filter-for-5e#1]
Might is be possible to add icons on the spellbook for each class so that you can see at a glance what spells belong to which class?

**Comment by MrEnigmamgine** [comment]
I played around with it and came up with a pretty rough draft.  If you want to, you can check it out early by cloning or downloading this repo into your modules folder.

Right now all it's doing is checking if there's a class item by the same name as the class you select on the spell.  If so, it replaces the spell icon with the class's icon.

I don't plan on pushing this update properly until I can wrap both methods behind a user setting and play with other ways to display the class's image.  But since that might be a week or two I figured this might help you out in the interim.

**Comment by GhostwheelX** [comment]
I don't think replacing the spell's icon with the class's icon is the way to go, since many players value customization of the icon incredibly highly from my experience.

Instead, I think something along the line of how Kandashi's [Spellbook Assistant Manager](https://www.foundryvtt-hub.com/package/spellbook-assistant-manager/) does it might be better.

**Comment by MrEnigmamgine** [comment]
Trust me, I get it.  That module is actually one of the first that came to mind when tackling this suggestion, and it's the module I tried using for my own game before writing this one.

Unfortunately there are some challenges in adopting a similar approach... most of them have to do with the idea of reformatting the entire spellbook table in order to add that column, and the others have to do with me being very much a novice developer.  Doing so adds a lot of complexity (for me at least), and complexity increases risk of something breaking.  I want this module to **work** (and right now the SAM module doesn't).  So I made the decision that whatever my solution is, it won't be adding a column to the table.

My next idea was to "stack" the class's icon behind the spell's icon like it was a card.  It would poke out enough that someone could see at a glance which class it was (assuming the colors were different enough) and maybe it would slide out to reveal itself fully if the mouse hovered over the spell.  There's some simplicity there since I could just inject a single div next to the spell's icon, and then try learning some css to handle the card effect. Pretty much every custom sheet is going to display the spells icon so there wasn't that much risk of this method breaking.

Anyway, somewhere along the line I accidentally made it so that the class image was replacing the spells image.  I realized that it was actually already solving the problem I was trying to solve.  So now I have an MVP (Minimum Viable Product).  I'm still curious if my original idea was any good so I'll keep trying for it, but this method IS shippable.

I realize that this method asks the user to exchange eye-candy with meaningful information, and that users really like their eye-candy.  That is why I'm going to wrap it in a setting, users will be able to choose which they prefer.

I want to point out that I'm not actually replacing the image in the spell's data, their custom image is still there and will still display in the chat and tabs that are not the spells tab (IE. Tidy 5e sheet's favorites).

-------------------------
Anyway.. this became a long post so TLDR:

This is the method I'm going to go with for now.
